/// The word lists, kept in step with `lexicon.ts` in the JavaScript package.
library;

import 'types.dart';

/// One word, stem or phrase, with the language it belongs to and the lowest strictness that turns it on.
class LexiconEntry {
  final String text;
  final Language language;
  final Strictness strictness;

  const LexiconEntry(this.text, this.language, this.strictness);

  @override
  String toString() => 'LexiconEntry($text, ${language.name}, ${strictness.name})';
}

List<LexiconEntry> _tag(Language language, Strictness strictness, List<String> texts) =>
    [for (final text in texts) LexiconEntry(text, language, strictness)];

/// Matched as whole words, after Nepali postpositions are taken off.
final List<LexiconEntry> words = List.unmodifiable([
  ..._tag(Language.english, Strictness.lenient, [
    'fuck',
    'fuk',
    'fck',
    'phuck',
    'shit',
    'shitty',
    'shithead',
    'bullshit',
    'bitch',
    'bastard',
    'ass',
    'asshole',
    'arsehole',
    'dumbass',
    'dick',
    'dickhead',
    'cunt',
    'whore',
    'slut',
    'cock',
    'pussy',
    'twat',
    'wanker',
    'retard',
    'fack',
    'fag',
    'fags',
    'faggot',
    'faggots',
    'fagot',
    'faggy',
    'nigger',
    'niggers',
    'nigga',
    'niggas',
    'tranny',
    'kike',
    'shitface',
    'shithole',
    'dipshit',
    'horseshit',
    'batshit',
    'apeshit',
    'jackass',
    'asshat',
    'asswipe',
    'cocksucker',
    'jizz',
    'dildo',
    'skank',
    'douchebag',
    'motherfucker',
    'bollocks',
    'bellend',
  ]),
  ..._tag(Language.english, Strictness.standard, [
    'piss',
    'idiot',
    'stupid',
    'moron',
    'crap',
    'crappy',
    'bugger',
    'douche',
    'jerk',
    'scumbag',
    'dumb',
    'wtf',
    'stfu',
    'tits',
    'boobs',
    'porn',
    'porno',
    'horny',
    'bimbo',
    'thot',
  ]),
  // Each of these is also an ordinary word: spic (span), chink (in the armour), dyke (a wall), hoe (a tool), cum
  // (laude), prick (a pin), damn.
  ..._tag(Language.english, Strictness.strict, [
    'spic',
    'chink',
    'dyke',
    'hoe',
    'cum',
    'prick',
    'damn',
    'rape',
  ]),
  ..._tag(Language.romanized, Strictness.lenient, [
    'muji',
    'mujhi',
    'muzi',
    'machikne',
    'machhikne',
    'mchikne',
    'mcikne',
    'machikney',
    'randi',
    'raandi',
    'rando',
    'rande',
    'radi',
    'lado',
    'lodo',
    'puti',
    'geda',
    'jatha',
    'jantha',
    'jathya',
    'chikne',
    'chikney',
    'bhalu',
    'khate',
    'khatey',
    'harami',
    'gandu',
    'chutiya',
    'chutia',
    'bhosdi',
    'bhosadi',
    'bhosdike',
    'bsdk',
    'madarchod',
    'behenchod',
    'bhenchod',
    'chhakka',
    'lauro',
    'gukhane',
    'gand',
    'gaand',
    'gandako',
    'lund',
    'lundra',
    'lundri',
    'chod',
    'chodna',
    'beshya',
    'hijada',
    'kamina',
    'haramzada',
    'turi',
    'pakhe',
    'condo',
    'kando',
    'chaak',
    'gula',
    'bajiya',
    'mji',
    'mzi',
    'mujj',
    'mooji',
    'moozi',
    'mcne',
    'mechikne',
    'laado',
    'puuti',
    'zatya',
    'chodeko',
    'toori',
    'kundo',
    'chhakke',
    'maxikne',
    'mxikne',
    'xutiya',
    'xutia',
    'chhutiya',
    'chootiya',
    'xikne',
    'jhant',
    'jhaant',
    'jhantu',
    'lauda',
    'lavda',
    'lawda',
    'loda',
    'lwado',
    'lwada',
    'bhosda',
    'bhosri',
    'chhinal',
    'chhinar',
    'besya',
    'maachod',
    'madarchood',
  ]),
  ..._tag(Language.romanized, Strictness.standard, [
    'kutta',
    'kutti',
    'kuttiya',
    'murkha',
    'badmas',
    'sala',
    'saley',
    'sali',
    'chhucho',
    'chhuchi',
    'gu',
    'thukk',
    'nalayak',
    'beijjat',
    'nikamma',
    'ghinlagdo',
    'nindaniya',
    'paji',
    'moot',
    'bhate',
    'chhura',
    'torpe',
    'mukhulla',
    'gobre',
    'bhusya',
    'dhurt',
    'gadha',
    'ullu',
    'badmash',
    'thukka',
    'haramkhor',
    'fataha',
  ]),
  ..._tag(Language.devanagari, Strictness.lenient, [
    'मुजी',
    'मुजि',
    'माचिक्ने',
    'मचिक्ने',
    'रण्डी',
    'रन्डी',
    'रंडी',
    'रांडी',
    'रण्डो',
    'राण्डे',
    'राडी',
    'लाडो',
    'लांडो',
    'पुती',
    'गेडा',
    'जाठा',
    'जांठा',
    'जाठ्या',
    'चिक्ने',
    'भालु',
    'खाते',
    'हरामी',
    'गान्डु',
    'गांडु',
    'चुतिया',
    'भोस्डी',
    'भोसडी',
    'भोस्डीके',
    'मादरचोद',
    'बहनचोद',
    'भेनचोद',
    'छक्का',
    'लौरो',
    'गुखाने',
    'गान्ड',
    'गाण्ड',
    'गान्डको',
    'लुंड',
    'लुण्ड',
    'लुन्ड्रा',
    'लुन्ड्री',
    'लोडो',
    'चोद',
    'चोद्ना',
    'चोदेको',
    'वेश्या',
    'हिजडा',
    'कमिना',
    'हरामजादा',
    'तुरी',
    'पाखे',
    'कोंडो',
    'काण्डो',
    'कुन्डो',
    'चाक',
    'गुला',
    'बजिया',
    'राण्डी',
    'गाण्डु',
    'भोसडीके',
    'गाण्डको',
    'कोन्डो',
    'छिनाल',
    'झांट',
    'झाँट',
    'लौडा',
    'लवडा',
  ]),
  ..._tag(Language.devanagari, Strictness.standard, [
    'कुत्ता',
    'कुत्ती',
    'कुत्तिया',
    'मुर्ख',
    'मूर्ख',
    'बदमास',
    'साला',
    'साले',
    'साली',
    'छुच्चो',
    'छुच्ची',
    'गु',
    'किचकिच',
    'थुक',
    'थुक्क',
    'नालायक',
    'बेइज्जत',
    'निकम्मा',
    'घिनलाग्दो',
    'निन्दनीय',
    'पाजी',
    'मूत',
    'भाते',
    'छुरा',
    'टोर्पे',
    'मुखुल्ला',
    'गोबरे',
    'भुस्या',
    'धूर्त',
    'गधा',
    'उल्लु',
    'उल्लू',
    'बदमाश',
    'थुक्का',
    'हरामखोर',
    'फटाहा',
  ]),
]);

/// Matched at the start of a word, so "fuck" also catches "fucking". Entries tagged strict also start ordinary
/// words or names: rand → Randip, cond → condition, kand → kanda / Kandel, lund → Lundberg. The ones they hit most
/// are in [allowed].
final List<LexiconEntry> stems = List.unmodifiable([
  ..._tag(Language.english, Strictness.lenient, [
    'fuck',
    'motherfuck',
    'bitch',
    'bastard',
    'asshol',
    'cunt',
    'whore',
    'slut',
    'wank',
    'retard',
    'shit',
    'nigger',
    'cocksuck',
    'bullshit',
    'dickhead',
    'douchebag',
    'jizz',
    'dildo',
  ]),
  ..._tag(Language.romanized, Strictness.lenient, [
    'machikn',
    'mchikn',
    'chutiy',
    'bhosd',
    'madarch',
    'behench',
    'bhench',
    'chikn',
    'chickn',
    'chod',
    'jath',
    'xutiy',
    'chhutiy',
    'maxikn',
    'jhant',
  ]),
  ..._tag(Language.romanized, Strictness.strict, [
    'rand',
    'cond',
    'kand',
    'lund',
  ]),
  ..._tag(Language.devanagari, Strictness.lenient, [
    'माचिक्न',
    'मचिक्न',
    'चुतिय',
    'भोस्ड',
    'मादरच',
    'बहनच',
    'भेनच',
    'चोद',
    'चिक्न',
    'रण्ड',
    'लुण्ड',
    'जाठ',
  ]),
  ..._tag(Language.devanagari, Strictness.strict, [
    'कोन्ड',
    'कान्ड',
  ]),
]);

/// Matched as a run of words separated by whitespace.
final List<LexiconEntry> phrases = List.unmodifiable([
  ..._tag(Language.romanized, Strictness.lenient, [
    'chaak ko pwal',
    'tero aama ko',
    'muji jasto',
    'lado khaye',
    'lado khos',
    'randi ko choro',
    'randi ko ban',
    'gand mara',
    'gand fatchya',
    'geda jasto',
    'geda khaya',
    'khatako choro',
    'bhaluko ban',
    'machikne khate',
    'teri maa ki',
    'teri ma ki',
  ]),
  ..._tag(Language.romanized, Strictness.standard, [
    'pesa garne',
    'sasto manche',
    'gu khane',
    'gu khaa',
  ]),
  ..._tag(Language.devanagari, Strictness.lenient, [
    'चाकको प्वाल',
    'चाक को प्वाल',
    'तेरो आमाको',
    'मुजी जस्तो',
    'लाडो खाए',
    'लाडो खोस्',
    'राण्डीको छोरो',
    'राण्डीको बान',
    'गाण्ड मरा',
    'गाण्ड फाट्या',
    'गेडा जस्तो',
    'गेडा खाया',
    'खातेको छोरो',
    'भालुको बान',
    'माचिक्ने खाते',
  ]),
  ..._tag(Language.devanagari, Strictness.standard, [
    'पेसा गर्ने',
    'सस्तो मान्छे',
  ]),
]);

/// Latin roots caught anywhere inside a word, not just at its start: dumbfuck, sonofabitch. Only roots that no
/// ordinary word contains are here; the few that do, like Scunthorpe, are in [allowed].
final List<LexiconEntry> infixes = List.unmodifiable([
  ..._tag(Language.english, Strictness.lenient, [
    'fuck',
    'cunt',
    'bitch',
    'whore',
    'nigger',
    'faggot',
    'jizz',
  ]),
]);

/// Ordinary words and names that a stem or an embedded root would otherwise flag. A word here is never flagged, with
/// or without a postposition (Randipko, Shitijlai), at any strictness.
const List<String> allowed = [
  'shitij',
  'shitiz',
  'shital',
  'shitala',
  'shitalpati',
  'shitanshu',
  'shiitake',
  'shitake',
  'shiite',
  'shiites',
  'shiitic',
  'niger',
  'nigeria',
  'nigerian',
  'nigerians',
  'nigerien',
  'snigger',
  'sniggers',
  'sniggered',
  'sniggering',
  'sniggerer',
  'scunthorpe',
  'randip',
  'randeep',
  'randhir',
  'randhawa',
  'random',
  'randomly',
  'randomness',
  'randomize',
  'randomized',
  'randy',
  'condition',
  'conditions',
  'conditional',
  'conditionally',
  'conditioner',
  'conditioning',
  'conditioned',
  'conduct',
  'conducts',
  'conducted',
  'conducting',
  'conductor',
  'conductors',
  'conduction',
  'conductive',
  'condense',
  'condensed',
  'condenser',
  'condemn',
  'condemned',
  'condolence',
  'condolences',
  'condiment',
  'kanda',
  'kandel',
  'kandu',
  'kandahar',
  'lundberg',
  'lundup',
];

/// The Nepali postpositions and plural endings taken off a Latin-script word, longest first.
const List<String> latinSuffixes = [
  'haruko',
  'harule',
  'sanga',
  'haru',
  'bata',
  'lai',
  'ko',
  'ki',
  'ka',
  'le',
  'ma',
  'ni',
  'ne',
  'yo',
];

/// The Nepali postpositions and plural endings taken off a Devanagari word, longest first.
const List<String> devanagariSuffixes = [
  'हरूको',
  'हरुको',
  'हरूले',
  'हरुले',
  'हरू',
  'हरु',
  'बाट',
  'सँग',
  'संग',
  'लाई',
  'को',
  'की',
  'का',
  'ले',
  'मा',
  'नि',
  'ने',
  'यो',
];

List<String> _texts(List<LexiconEntry> entries, {required bool latin}) => List.unmodifiable([
      for (final e in entries)
        if ((e.language != Language.devanagari) == latin) e.text
    ]);

/// Every Latin-script word, at every strictness.
final List<String> latinWords = _texts(words, latin: true);

/// Every Latin-script stem, at every strictness.
final List<String> latinStems = _texts(stems, latin: true);

/// Every Latin-script phrase, at every strictness.
final List<String> latinPhrases = _texts(phrases, latin: true);

/// Every Latin-script root matched anywhere inside a word, at every strictness.
final List<String> latinInfixes = _texts(infixes, latin: true);

/// Every Devanagari word, at every strictness.
final List<String> devanagariWords = _texts(words, latin: false);

/// Every Devanagari stem, at every strictness.
final List<String> devanagariStems = _texts(stems, latin: false);

/// Every Devanagari phrase, at every strictness.
final List<String> devanagariPhrases = _texts(phrases, latin: false);
